FROM nginx:1.15.0-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

### se não exister pelo menos o arquivo index.php, vamos receber 404. 
### Entao assim resolvemos, mesmo que esteja vazio
RUN mkdir /var/www/html -p && touch /var/www/html/index.php
